<?php echo $this->render('header.phtml') ?>
<body>
<header class="indent">
<div class="container">
 <h1 class="navbar-brand navbar-brand_"><a href="<?php echo $this->baseUrl(); ?>"><img src="<?php echo $this->baseUrl(); ?>/images/Logo.png" alt="logo"></a></h1>
  <nav class="navbar navbar-default navbar-static-top tm_navbar clearfix" role="navigation">
   <ul class="nav sf-menu clearfix">
    <li class="active"><a  href="javascript:history.back()"> Regresar</a></li>
   </ul>
  </nav>
</div>
</header>
<div class="global">
 <div class="slider">
  <div class="camera_wrap">
   <div data-src="<?php echo $this->baseUrl(); ?>/images/FondoAgenda.jpg"><div class="camera-caption fadeIn"><p class="description">Información del Contacto</p></div></div>
  </div>
  </div>
<div class="container">
 <div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12 carousel-box">
   <div class="list_carousel1 responsive clearfix">
    <ul id="foo1">
     <li>
      <div class="row">
       <div class="box">
        <form id="contact-form" >
         <div class="contact-form-loader"></div>
          <fieldset>

    <?php foreach ($this->datos as $d) : ?>

<label class="name form-div-1">
Nombre:
</label>
<label class="name form-div-1">
<input type="text" name="name"  value="<?php echo  $d["Nombre"];?>" readonly />
</label>
<label class="name form-div-2">
Apellido Paterno:
</label>
<label class="email form-div-2">
<input type="text" name="email"  value="<?php echo  $d["Paterno"];?>" readonly />
</label>
<label class="name form-div-1">
Apellido Materno:
</label>
<label class="phone form-div-1">
<input type="text" name="phone"  value="<?php echo  $d["Materno"];?>" readonly />
</label>
<label class="name form-div-2">
E-mail:
</label>
<label class="phone form-div-2">
<input type="text" name="phone"  value="<?php echo  $d["Email"];?>" readonly />
</label>
<label class="name form-div-1">
Dirección:
</label>
<label class="phone form-div-1">
<input type="text" name="phone"  value="<?php echo  $d["Direccion"];?>" readonly />
</label>
<label class="name form-div-1">
Colonia:
</label>
<label class="phone form-div-1">
<input type="text" name="phone"  value="<?php echo  $d["Colonia"];?>" readonly />
</label>
<label class="name form-div-2">
Delegación/Municipio:
</label>
<label class="phone form-div-2">
<input type="text" name="phone"  value="<?php echo  $d["Poblacion"];?>" readonly />
</label>
<label class="name form-div-1">
Estado:
</label>
<label class="phone form-div-1">
<input type="text" name="phone"  value="<?php echo  $d["Estado"];?>" readonly />
</label>
<label class="name form-div-2">
Código Postal:
</label>
<label class="phone form-div-2">
<input type="text" name="phone"  value="<?php echo  $d["CP"];?>" readonly />
</label>
<label class="name form-div-1">
Teléfono casa:
</label>
<label class="phone form-div-1">
<input type="text" name="phone"  value="<?php echo  $d["Telcasa"];?>" readonly />
</label>
<label class="name form-div-2">
Celular:
</label>
<label class="phone form-div-2">
<input type="text" name="phone"  value="<?php echo  $d["Celular"];?>" readonly />
</label>
<label class="name form-div-1">
Teléfono Oficina:
</label>
<label class="phone form-div-1">
<input type="text" name="phone"  value="<?php echo  $d["TelOficina"];?>" readonly />
</label>
<label class="name form-div-2">
Otro teléfono:
</label>
<label class="phone form-div-2">
<input type="text" name="phone"  value="<?php echo  $d["OtroTel"];?>" readonly />
</label>

 <?php endforeach; ?>

          </fieldset>
         </form>
        </div>
       </div>
      </li>
     </ul>
    </div>
   </div>
  </div>
 </div>
</div>

<?php echo $this->render('footer.phtml') ?>

<script type="text/javascript">
			$(document).ready(function(){ 
			
			$(window).scroll(function(){
				if ($(this).scrollTop() > 100) {
					$('.scrollup').fadeIn();
				} else {
					$('.scrollup').fadeOut();
				}
			}); 
			
			$('.scrollup').click(function(){
				$("html, body").animate({ scrollTop: 0 }, 600);
				return false;
			});
 
		});
</script>


</body> 
</html>